/**
 * The styled-components `emit()` module assembler (§8) — writes **TS/JS modules**, not a stylesheet.
 *
 * What lands on disk (self-contained — a downstream app imports these and drops refract at runtime):
 *  - **theme.ts** — the literal theme object (`export const theme = { … } as const`) + the flat, tree-
 *    shakeable `css` recipe consts + a grouped `recipes` barrel + (if the raw defines `globals`) a
 *    `GlobalStyle`. `emit: "split"` peels the recipes into `recipes.ts` and the `GlobalStyle` into
 *    `global.ts`.
 *  - **media.ts** (always) / **scheme.ts** (iff modes ride `prefers-color-scheme`) — vendored tagged
 *    templates with this theme's concrete `@media` strings baked in.
 *  - **theme.d.ts** (iff `language: "ts"`) — augments styled-components' `DefaultTheme` from `typeof theme`.
 *  - **color-math.ts** is materialized by the shared build plumbing (`emitTheme` + `VENDOR_HELPERS`),
 *    not here — this module only wires the `import`.
 */
import type { EmitOutput } from "@theme-registry/refract";
import type { MediaDescriptor, MediaVariant } from "@theme-registry/refract";

const VARIANTS: ReadonlyArray<MediaVariant> = ["min", "max", "exact"];

/** color-math exports surfaced on `theme` when `helpers: ["color-math"]` is opted in. */
export const COLOR_MATH_ATTACH: ReadonlyArray<string> = ["lighten", "darken", "alpha"];

/**
 * Generate a self-contained SC media-helper module (source text) for `breakpoints`, reading the
 * concrete `@media` query strings from the already-built core {@link MediaDescriptor}.
 */
export const vendorMediaHelper = <TBreakpoint extends string>(
  breakpoints: Record<TBreakpoint, number>,
  media: MediaDescriptor<TBreakpoint>,
): string => {
  const keys = (Object.keys(breakpoints) as TBreakpoint[]).sort(
    (a, b) => breakpoints[a] - breakpoints[b],
  );

  const groups = keys
    .map(key => {
      const group = media[key];
      const variants = VARIANTS.map(
        variant => `    ${variant}: wrap(${JSON.stringify(group?.[variant] ?? "")}),`,
      ).join("\n");
      return `  ${JSON.stringify(key)}: {\n${variants}\n  },`;
    })
    .join("\n");

  return `// Vendored, self-contained styled-components media helper (generated by @theme-registry/refract).
// Only dependency: styled-components. Concrete @media strings are baked in for this theme's breakpoints.
import { css } from "styled-components";

const wrap = (query) => {
  const fn = query
    ? (styles, ...interpolations) => css\`\${query} { \${css(styles, ...interpolations)} }\`
    : (styles, ...interpolations) => css\`\${css(styles, ...interpolations)}\`;
  fn.query = query;
  return fn;
};

export const media = {
${groups}
};

export default media;
`;
};

// ---------------------------------------------------------------------------
// Module assembly
// ---------------------------------------------------------------------------

/** One recipe ready to serialize: its export identifier + its `css\`…\`` body source. */
export interface RecipeEmit {
  readonly exportName: string;
  readonly body: string;
}

/** Everything the assembler needs, prepared by the adapter's bind. */
export interface ScEmitInputs {
  readonly language: "ts" | "js";
  readonly emitMode: "single" | "split";
  readonly helpers: readonly string[];
  readonly usesScheme: boolean;
  /** The `export const theme = <this> as const` body (subsystems + modes + trailing refs). */
  readonly themeObjectBody: string;
  /** Recipes in dependency-safe order (a composed recipe's references precede it). */
  readonly recipes: readonly RecipeEmit[];
  /** The grouped `export const recipes = { … } as const` barrel body. */
  readonly recipesBarrelBody: string;
  /** The `createGlobalStyle\`…\`` body, if the raw defines `globals`. */
  readonly resetBody?: string;
  readonly vendorMedia: string;
  readonly vendorScheme?: string;
}

const usesColorMath = (helpers: readonly string[]): boolean => helpers.includes("color-math");

/** The `import … from "styled-components"` line for the file that carries recipes / GlobalStyle. */
const scImport = (needsCss: boolean, needsGlobal: boolean): string => {
  const names = [needsCss ? "css" : "", needsGlobal ? "createGlobalStyle" : ""].filter(Boolean);
  return `import { ${names.join(", ")} } from "styled-components";`;
};

/** The imports the theme object needs (`media`, optional `scheme`, optional color-math helpers). */
const themeImports = (inputs: ScEmitInputs): string[] => {
  const lines = [`import { media } from "./media";`];
  if (inputs.usesScheme) lines.push(`import { scheme } from "./scheme";`);
  if (usesColorMath(inputs.helpers)) {
    lines.push(`import { ${COLOR_MATH_ATTACH.join(", ")} } from "./color-math";`);
  }
  return lines;
};

const themeConst = (body: string): string => `export const theme = ${body} as const;`;

const recipeConsts = (recipes: readonly RecipeEmit[]): string =>
  recipes.map(r => `export const ${r.exportName} = css\`\n${r.body}\n\`;`).join("\n\n");

const recipesBarrel = (body: string): string => `export const recipes = ${body} as const;`;

const globalStyle = (body: string): string => `export const GlobalStyle = createGlobalStyle\`\n${body}\n\`;`;

const themeDts = (): string =>
  `import "styled-components";
import type { theme } from "./theme";

declare module "styled-components" {
  export interface DefaultTheme extends Readonly<typeof theme> {}
}
`;

/** Assemble the SC emit output (files + vendored helpers) from the prepared inputs. */
export const buildScEmit = (inputs: ScEmitInputs): EmitOutput => {
  const files: Record<string, string> = {};
  const vendorHelpers: Record<string, string> = { "media.ts": inputs.vendorMedia };
  if (inputs.vendorScheme) vendorHelpers["scheme.ts"] = inputs.vendorScheme;

  const hasRecipes = inputs.recipes.length > 0;
  const hasReset = inputs.resetBody !== undefined;

  if (inputs.emitMode === "single") {
    const parts: string[] = [];
    parts.push([scImport(hasRecipes, hasReset), ...themeImports(inputs)].join("\n"));
    parts.push(themeConst(inputs.themeObjectBody));
    if (hasRecipes) {
      parts.push(recipeConsts(inputs.recipes));
      parts.push(recipesBarrel(inputs.recipesBarrelBody));
    }
    if (hasReset) parts.push(globalStyle(inputs.resetBody!));
    files["theme.ts"] = parts.join("\n\n") + "\n";
  } else {
    // split — theme / recipes / global in separate files.
    files["theme.ts"] = [themeImports(inputs).join("\n"), themeConst(inputs.themeObjectBody)].join("\n\n") + "\n";
    if (hasRecipes) {
      files["recipes.ts"] =
        [scImport(true, false), recipeConsts(inputs.recipes), recipesBarrel(inputs.recipesBarrelBody)].join("\n\n") + "\n";
    }
    if (hasReset) {
      files["global.ts"] = [scImport(false, true), globalStyle(inputs.resetBody!)].join("\n\n") + "\n";
    }
  }

  if (inputs.language === "ts") files["theme.d.ts"] = themeDts();

  // A `js` emit writes `.js` module names (the source is plain JS — no annotations are generated).
  if (inputs.language === "js") {
    for (const name of Object.keys(files)) {
      if (name.endsWith(".ts") && !name.endsWith(".d.ts")) {
        files[name.replace(/\.ts$/, ".js")] = files[name];
        delete files[name];
      }
    }
    for (const name of Object.keys(vendorHelpers)) {
      vendorHelpers[name.replace(/\.ts$/, ".js")] = vendorHelpers[name];
      delete vendorHelpers[name];
    }
  }

  return { files, vendorHelpers };
};
