/**
 * SC colour-scheme tagged templates (§8) — the `theme.scheme.dark\`…\`` half of the appearance-mode
 * (§10.3) realization, parallel to `media.ts`. A recipe's dark block interpolates
 * `${({ theme }) => theme.scheme.dark\`…\`}`, which wraps its body in
 * `@media (prefers-color-scheme: dark) { … }`. Only `dark` / `light` ride `prefers-color-scheme`
 * (a `[data-theme]` toggle handles any other named mode — that path uses a plain nested selector,
 * not this helper).
 *
 * Two forms, like media: a **runtime** wrapper (`wrapSchemeHelper`) put on the live `theme.scheme`,
 * and a **vendored** self-contained module (`vendorSchemeHelper`) written by `emit()` so a downstream
 * app keeps `theme.scheme` after it drops refract (its only dependency is `styled-components`).
 */
import { css } from "styled-components";
import type { Interpolation, RuleSet } from "styled-components";

/** The concrete `@media (prefers-color-scheme: …)` string for a realizable mode. */
export const PREFERS: Record<string, string> = {
  dark: "@media (prefers-color-scheme: dark)",
  light: "@media (prefers-color-scheme: light)",
};

/** Which authored modes ride `prefers-color-scheme` (the ones this helper realizes). */
export const mediaEligibleModes = (modeNames: readonly string[]): string[] =>
  modeNames.filter(mode => mode in PREFERS);

type SchemeTemplate = (
  styles: TemplateStringsArray,
  ...interpolations: Interpolation<object>[]
) => RuleSet<object>;

/** A scheme tagged-template that also carries the raw `@media (prefers-color-scheme: …)` it wraps. */
export type SchemeTemplateWithQuery = SchemeTemplate & { readonly query: string };

/** The wrapped `theme.scheme` — one tagged template per realizable mode (`dark` / `light`). */
export type SchemeHelper = Record<string, SchemeTemplateWithQuery>;

const buildTemplate = (query: string): SchemeTemplate => (styles, ...interpolations) =>
  css`
    ${query} {
      ${css(styles, ...interpolations)}
    }
  `;

/** Build the runtime `theme.scheme` for the given realizable modes. */
export const wrapSchemeHelper = (modeNames: readonly string[]): SchemeHelper => {
  const helper: SchemeHelper = {};
  for (const mode of mediaEligibleModes(modeNames)) {
    const query = PREFERS[mode];
    helper[mode] = Object.assign(buildTemplate(query), { query }) as SchemeTemplateWithQuery;
  }
  return helper;
};

/** Generate the self-contained vendored `scheme.ts` source for the given realizable modes. */
export const vendorSchemeHelper = (modeNames: readonly string[]): string => {
  const entries = mediaEligibleModes(modeNames)
    .map(mode => `  ${JSON.stringify(mode)}: wrap(${JSON.stringify(PREFERS[mode])}),`)
    .join("\n");

  return `// Vendored, self-contained styled-components colour-scheme helper (generated by @theme-registry/refract).
// Only dependency: styled-components. Realizes appearance modes as prefers-color-scheme media blocks.
import { css } from "styled-components";

const wrap = (query) => {
  const fn = (styles, ...interpolations) => css\`\${query} { \${css(styles, ...interpolations)} }\`;
  fn.query = query;
  return fn;
};

export const scheme = {
${entries}
};

export default scheme;
`;
};
